version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/Deepti_auto_AWS

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60

