version: 0.0
os: linux

files:
  - source: /
    destination: /opt/biki-sports

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60

